### ISSUE TITLE
Docs on running Esquio UI in Docker

### ISSUE THREAD

**Issue by jmezach** [Xabaril/Esquio#124]
Are there any docs yet on how to run the Esquio UI in Docker? I can start it just fine, but I'm not able to login, probably because there's no database configured. Not sure how to configure that though, or even what my options are storing the database?

**Comment by unaizorrilla** [comment]
Hi @jmezach 

There are some environment variables to configure

-e ConnectionStrings__Esquio=[your sql server connection string]
-e Security__OpenId__Authority=[your authority, for example https://demo.identityserver.io]
-e Security__OpenId__ClientId=[your client id]
-e Security__OpenId__ResponseType=[your openid flow response type to use, for example code]
-e Security__OpenId__Audience=[your security audience]


You can check the settings that we use on demo

https://github.com/Xabaril/Esquio/blob/master/src/Esquio.UI.Host/appsettings.json 

 Also, if you want to tests Esquio on local, you can do directly with our compose 

**docker-compose -f .\build\docker-compose-demo-with-ui.yml up**

This build and up the demo app and the Esquio UI with dependencies ( sqlserver ) to easly test Esquio.


I hope @carlosrecuero  can add docker information to our docs soon!

**Comment by jmezach** [comment]
Thanks @unaizorrilla, that helped. I've managed to run Esquio UI with docker-compose locally and it works great. Definitely a good idea to add this to the docs so that people can get started quickly.
