### ISSUE TITLE
Why netstandard 2.1 ?

### ISSUE THREAD

**Issue by suddenelfilio** [Xabaril/Esquio#129]
Is there a specific reason that you only started targetting from netstandard 2.1 effectivly limiting this to .net core 3.x? Most of your dependecies support netstandard 2.0 which keeps them open for a broader spectrum of consumers (even in the full .net framework via 4.8). I understand that you would like the UI and api to be run as .net core 3.x apps, but maybe a client could allow for a more relaxed netstandard 2.0 version? Or am I missing something?

**Comment by unaizorrilla** [comment]
Hi @suddenelfilio 

Thanks for fill this issue! 

Esquio is created with diagnostics / observability  from the begining with log, perf counters and EventSource. This come from System.Diagnostic.Trace and this is .netstandard2.1 so, this is limiting going down to 2.0,

**Comment by suddenelfilio** [comment]
aha I see :-)
