### ISSUE TITLE
Inconsistent behavior adding and editing products

### ISSUE THREAD

**Issue by modesto** [Xabaril/Esquio#131]
I have found two abnormal behaviors related to products page.

1) There is some kind of validation inconsistency with the "New product" modal window. "Save changes" button is being enabled even when validations are invalid. It occurs when I leave name or description fileds untouched.

2) I can edit product's description and leave it empty, saving correctly.

Here is an animated gif that shows it:

![esquio-product-bug](https://user-images.githubusercontent.com/490204/84715803-7ce48780-af69-11ea-8654-d6d7e300d1c8.gif)

I tried to take a look at the code, but I practically don't know blazor :(

**Comment by unaizorrilla** [comment]
Fixed on features/esquio31 will be available on next Esquio minor version

**Comment by modesto** [comment]
I've been doing some tests and it appears that the 2nd example is fixed but not the first.

I have also verified that first and second problems also occurs creating a new feature or editing an existing one.
