### ISSUE TITLE
How can one setp the schema for the database

### ISSUE THREAD

**Issue by gkfischer** [Xabaril/Esquio#135]
In https://github.com/Xabaril/Esquio/issues/89 it is mentioned that the schema can be set by some option in V3, but I can't figure out how to do that. Could someone help me out here please?

**Comment by unaizorrilla** [comment]
Hi @gkfischer 

Let me check to show a guidance about this! I'm not sure all is working100% with migrations!

**Comment by gkfischer** [comment]
Thanks, I can manage with the migration update in the meantime
