### ISSUE TITLE
Generic Database Store?

### ISSUE THREAD

**Issue by Kronos11** [Xabaril/Esquio#137]
It would be extremely helpful if all of the Entity Store logic was separated out and one could simply add in the Entity Framework provider of your choice, for example npgsql or a mysql provider. This would allow me to use the UI without any work whatsoever.

**Comment by unaizorrilla** [comment]
Yeap, agree !! 

We have this on our roadmap, but this time we are so busy :( A PR is welcome if you want, if not we try to do a soon as posible!

**Comment by Kronos11** [comment]
I'm willing to take a crack at this tomorrow I have some time.
What is the general approach you were thinking?
Create different projects for the different db providers? and have separate migrations for each?
I see need to have a script that would handle the migrations in that case.

Maybe allow the user to setup their own Factory to create the DbContext and allow them to put whatever they want as an options builder? Seems like this is more flexible, but there might be some other issues I'm not aware of?

**Comment by unaizorrilla** [comment]
Well, the aproach could be some like

 - Create diferent dbcontext  for each database provider, A for Sql Server B:A for postgress 
 - Use the factory to register the specified context depending on some configuration, AddDbcontext<A> and AddDbcontext<A,B> for postgress
  - Put the migrations on Infrastructure/Data/Migrations/A and Infrastructure/Data/Migrations/B


Look ok?

**Comment by Kronos11** [comment]
Sounds good, so each time there is a new db provider we will need to add a new project?

**Comment by unaizorrilla** [comment]
Merged on master, now as 4.0 working version!
