### ISSUE TITLE
IsEnabledAsync for specific product and environments

### ISSUE THREAD

**Issue by gkfischer** [Xabaril/Esquio#140]
Environments are a new addition I'm realy hapy about, but it seems there is still a lack of possibilities to acutally use them, or I can't once again figure out how to use them properly.

The IFeatureService interface only defines 
``` C#
Task<bool> IsEnabledAsync(string featureName, CancellationToken cancellationToken = default);
```
but no 
``` C#
Task<bool> IsEnabledAsync(string featureName, string environmentName,  string productName, CancellationToken cancellationToken = default);
```
Am I missing something, or asked otherwise: how can I make use of the environment feature when I want to get the status of a feature?

**Comment by unaizorrilla** [comment]
Hi @gkfischer 

The IFeatureService internally use the configured product name when you use AddEsquio extension method, you don't need to specify this on every call. If you need a feature enabled or not depending on ASP.NET CORE Environment Variable you can use the [HostEnvironmentToggle](https://github.com/Xabaril/Esquio/blob/master/src/Esquio.AspNetCore/Toggles/HostEnvironmentToggle.cs) for that!

Unai

**Comment by gkfischer** [comment]
Thanks, that pointed me in the right direction. I think I found a bug regarding toggle parameters of non default deployments along the way, but I'll open another issue for that.
