### ISSUE TITLE
Unable to create toggles after creating a default deployment name with less than 5 characters

### ISSUE THREAD

**Issue by Kronos11** [Xabaril/Esquio#156]
The validation for deployment name doesn't trigger when creating a new Product
So when going to create a toggle in the product it will always fail

**Comment by unaizorrilla** [comment]
On v4 (master branch)

**Comment by unaizorrilla** [comment]
Pushed the deployment name validator on add new product window! 

Please close the issue if this solve the problem!

**Comment by Kronos11** [comment]
Fixed!
