### ISSUE TITLE
FromToToggle throws exception if no To date specified

### ISSUE THREAD

**Issue by Kronos11** [Xabaril/Esquio#163]
I was expecting that this toggle would set some max date toggle if no date was provided. This unfortunately is not the case and it throws an exception.
`System.Collections.Generic.KeyNotFoundException: The given key 'To' was not present in the dictionary.`

**Comment by unaizorrilla** [comment]
Well, To is a required parameter and the UI will show a required validation if is not set!

https://github.com/Xabaril/Esquio/blob/485b23ca8c413d1b7386c394a26e9ac0ba85823e/src/Esquio/Toggles/FromToToggle.cs#L14

I see your PR to set default DateTime.MaxValue for To parameter, let me some days (I'm on holidays) to checkout and review
