### ISSUE TITLE
Error while registering custom toggles in different assembly

### ISSUE THREAD

**Issue by CrahunGit** [Xabaril/Esquio#165]
Seems it tries to find the custom toggles from the current assembly where the ToggleTypeActivator is insetead of the registered assembly. The only solution I've found is replace the IToggleTypeActivator with my own implementation on the main project.

**Comment by unaizorrilla** [comment]
Hi @CrahunGit 

I update samples (https://github.com/Xabaril/Esquio/blob/master/samples/GettingStarted.AspNetCore.Toggles) to include using custom toggles. But the idea is:

 - Register assembly with toggles 

https://github.com/Xabaril/Esquio/blob/400a6399e1a5f1c534f42baaf7c8f68285c8e969/samples/GettingStarted.AspNetCore.Toggles/Startup.cs#L25

-  Configure it using fully qualified names

https://github.com/Xabaril/Esquio/blob/400a6399e1a5f1c534f42baaf7c8f68285c8e969/samples/GettingStarted.AspNetCore.Toggles/appsettings.json#L27

**Comment by CrahunGit** [comment]
You're right. Now it works as expected. I didn't take account about the fully qualified name
