### ISSUE TITLE
Badge for in-browser demo

### ISSUE THREAD

**Issue by kklin** [Xabaril/Esquio#166]
We discussed over email that a badge that lets visitors poke around Esquio without downloading anything might be useful.

I'll update this issue once I've implemented the hosting.

**Comment by unaizorrilla** [comment]
Hi @kklin 

Thanks, sounds good!

**Comment by kklin** [comment]
Hi @unaizorrilla!

We’ve put together the first version of the demo badge. There's an example [here](https://github.com/kelda/node-todo):
 the badge links to https://kelda.io/preview-env/?repo=https://github.com/kelda/node-todo.git&service=web&port=8080. All the configuration is in the query params.

<img width="1419" alt="Screen Shot 2020-09-13 at 3 05 59 PM" src="https://user-images.githubusercontent.com/1811185/93029847-312a9400-f5d3-11ea-99f7-67df5c50aeb6.png">

We need to do more work before it’ll work with Esquio but would love to hear what you think so far. Is the UX what you were imagining? Does it still seem useful?

**Comment by unaizorrilla** [comment]
Hi @kklin 

Looks really cool!! I'm playing with this and seem awesome!! I like this to show the Esquio App and UI without downloading anything.!

If there is something to help, please let me know!

Unai

**Comment by kklin** [comment]
Wonderful thanks!

**Comment by kklin** [comment]
Hi @unaizorrilla, I'm looking at booting https://github.com/Xabaril/Esquio/blob/48e32a2f42b590df2c112fbdce9a354de573eb74/build/docker-compose-demo-with-ui-mysql.yml and noticed that it builds the images for app and ui locally. Blimp can support building locally but that will obviously mean it'll take longer for the demo environment to boot.

Another option would be to prebuild and push images, and have the demo env just pull them. But that would mean more overhead for you as a maintainer.

What do you think of the two options?

**Comment by kklin** [comment]
Also, when I boot the demo and login with alice / alice, I don't see any toggles in the Esquio UI. Is this expected?

<img width="1070" alt="Screen Shot 2020-09-15 at 3 44 36 PM" src="https://user-images.githubusercontent.com/1811185/93272491-72a17780-f76a-11ea-9d21-c1141ca6a213.png">

**Comment by unaizorrilla** [comment]
Hi @kklin 

 - Esquio UI is also on DockerHub https://hub.docker.com/r/xabarilcoding/esquioui but we use build image on local compose to obviously rebuild with changes
 - We can add also esquio app to docker hub and create a new compose using this images to reduce the time to tests what Esquio is ¿sounds good?

**Comment by unaizorrilla** [comment]
> Also, when I boot the demo and login with alice / alice, I don't see any toggles in the Esquio UI. Is this expected?
> 
> <img alt="Screen Shot 2020-09-15 at 3 44 36 PM" width="1070" src="https://user-images.githubusercontent.com/1811185/93272491-72a17780-f76a-11ea-9d21-c1141ca6a213.png">

Yeap, Esquio UI is empty at the begining, the demo here is adding MatchScore, DarkMode ( the configured features on App Demo)  to see the changes

**Comment by kklin** [comment]
> We can add also esquio app to docker hub

Sounds good! I'll play around with it.

> the demo here is adding MatchScore, DarkMode

Are there any docs on how to get these features to appear in the Esquio UI so that they can be toggled? The only docs I could find on the UI were about installing it

**Comment by unaizorrilla** [comment]
Nope on docs but I can arrange a short meeting with you to show case it or checkout this videos

https://www.youtube.com/watch?v=qotnVlgYd8c&feature=youtu.be&list=PL1rZQsJPBU2St9-Mz1Kaa7rofciyrwWVx&t=225

https://www.youtube.com/watch?v=VCGZZOFaPL0 (Spanish)

**Comment by unaizorrilla** [comment]
Hi @kklin 

This compose works with public images on docker hub, hope this help

https://github.com/Xabaril/Esquio/blob/master/build/docker-compose-demo-with-ui-sqlserver-with-reference-images.yml

**Comment by kklin** [comment]
I'll take a look at the videos first but I'll reach out if I can't figure it out. Thanks!
