### ISSUE TITLE
Web Login only works on fresh instance of browser with no cache

### ISSUE THREAD

**Issue by Kronos11** [Xabaril/Esquio#167]
Authentication doesn't seem to work properly using AAD except if you clear the cache/session data.
Is something being stored that needs to be removed upon a new login attempt?

**Comment by unaizorrilla** [comment]
On 4.0 preview? Let me check this weekend!

**Comment by unaizorrilla** [comment]
I'm debugging the issue, the EvaluatingAuthorization on Authentication.razor seems that throw on get my info and a infinite loop is produced! Catching the exception and move to not allowed looks good but I'm testing it

**Comment by unaizorrilla** [comment]
Hi @Kronos11 

Just added a commit that work around this issue ¿can you test it?

I prepare a new compose file for aad to test without debug, please close the issue if all is ok!

https://github.com/Xabaril/Esquio/blob/master/build/docker-compose-demo-with-ui-sqlserver.aad.yml

If works well we can  release a new preview this week and well, test all scenarios to release the 4.0 final version!


Thanks for your help testing Esquio!!
Unai

**Comment by Kronos11** [comment]
Validated it is working as expected! Thanks for the quick fix.
