### ISSUE TITLE
Esquio: Warning: DefaultToggleTypeActivator can't resolve the toggle type Esquio.AspNetCore.Toggles.HostEnvironmentToggle.

### ISSUE THREAD

**Issue by eyassud** [Xabaril/Esquio#200]
Hello:

I have the settings below, but at runtime the 'HostEnvironmentToggle' is never loaded and thus always returns false for the feature.

I have a basic VS solution that reproduces the issue: See https://github.com/eyassud/EsquioWeApiDemo.git

"Esquio": {
    "Products": [
      {
        "Name": "default",
        "Features": [
          {
            "Name": "gpi",
            "Enabled": true,
            "Toggles": [
              {
                "Type": "Esquio.AspNetCore.Toggles.HostEnvironmentToggle",
                "Parameters": {
                  "Environments": "Staging;Development"
                }
              }
            ]
          }
        ]
      }
    ]
  }

**Comment by eyassud** [comment]
> Hi @eyassud
> 
> Witch version of Esquio? latest?

Yes, the latest .net core version

**Comment by eyassud** [comment]
> Hello:
> 
> I have the settings below, but at runtime the 'HostEnvironmentToggle' is never loaded and thus always returns false for the feature.
> 
> I have a basic VS solution that reproduces the issue: See https://github.com/eyassud/EsquioWeApiDemo.git
> 
> "Esquio": { "Products": [ { "Name": "default", "Features": [ { "Name": "gpi", "Enabled": true, "Toggles": [ { "Type": "Esquio.AspNetCore.Toggles.HostEnvironmentToggle", "Parameters": { "Environments": "Staging;Development" } } ] } ] } ] }

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/11150065/161580107-3258145a-8195-442b-9f2f-9d7b4ae8ca34.png">

**Comment by eyassud** [comment]
> Hi
> 
> Please set Type as "Esquio.AspNetCore.Toggles.HostEnvironmentToggle, Esquio.AspNetCore" ie , fully qualified type name!
> 
> Let me know if this is working for you!

No luck with fully qualified name.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/11150065/161582776-35825896-363a-4da0-826e-60c28d9325e8.png">

**Comment by eyassud** [comment]
> There is not fully qualified use type, assembly like
> 
> Esquio.AspNetCore.Toggles.HostEnvironmentToggle, Esquio.AspNetCore
> 
> just tested and work a fine!

Are you using VS 2022 and .NET 6? Do you have a link to a working example on GitHub?

**Comment by unaizorrilla** [comment]
Hi!

Just pushed this on MVC Sample

https://github.com/Xabaril/Esquio/blob/master/samples/GettingStarted.AspNetCore.Mvc/appsettings.json

Unai
