### ISSUE TITLE
Improve tokenization

### ISSUE THREAD

**Issue by 3lcarry** [Xabaril/Esquio#47]
On the scenarios where all your feature toggle are by username enable to the 50%, always the same users has them enable. Add the possibility to use the username + the feature name to randomize the users per feature.

**Comment by unaizorrilla** [comment]
Hi @3lcarry 

Your question is about add entropy to the partitioner to avoid have the same result for all features using the partitioner for the same value ( ie, username )?

**Comment by unaizorrilla** [comment]
done
