### ISSUE TITLE
How do I initialize DB

### ISSUE THREAD

**Issue by risogolo** [Xabaril/Esquio#89]
Trying to get empty DB tables created with Esquio.EntityFrameworkCore.Store
I'm unable to do it, It seems to be created when I use that Esquio.UI, but I might dont want to use it
Is it possible to automaticaly create DB if it does not exist, therefore I can use sql script or use EF migrations to insert data there

``` 
services.AddEsquio(setup =>
            {
                setup.RegisterTogglesFromAssemblyContaining<ClaimValueToggle>();
            }
                )
                .AddAspNetCoreDefaultServices()
                .AddEntityFrameworkCoreStore(options =>
                {
                    options.DefaultSchema = "RCM";
                    options.ConfigureDbContext = o => { o.UseSqlServer(Configuration["ConnectionStrings:MSSQLConnection"]); };
                });```

**Comment by unaizorrilla** [comment]
Hi @risogolo 

Esquio UI, the free admin tool to manage Esquio products/features/toggles, initialize and migrate database to latest version. You can view migrate and seed on:

https://github.com/Xabaril/Esquio/blob/3edb71d683df4a4ba522e38f0ecebb1927ec768c/src/Esquio.UI/Program.cs#L14

This MigrateDbContext Extension method do migration and seed (if exist)

https://github.com/Xabaril/Esquio/blob/master/src/Esquio.UI/Infrastructure/Extensions/IHostExtensions.cs

If you plan to use database without UI, creating your own tool to admin products/features/toggles, you can add migrations ( dotnet ef migrations add ... ) from the EF configuration store to your project.

In Esquio 3.X, on development, we are chaning some things related with the store, all feedback is welcome for next version!!


Thanks
Unai

**Comment by risogolo** [comment]
Hello, thank for you response, I guess that method should exist in the libray itself or in the library for SqlStore, not it in Esquio.UI, also if you are planning to change that please do also DB schema name configurable, thank  you very much

**Comment by unaizorrilla** [comment]
Hi risogolo!

Yeap, on V3 we are working on it, and probably, the store will be only for configuration and distributed ( to UI using http api ) because this enable distributed scenarios and also some multi-tenancy.

On 2.2 you can use StoreOptions to configure DefaultSchema and Table Names

https://github.com/Xabaril/Esquio/blob/master/src/Esquio.EntityFrameworkCore.Store/Options/StoreOptions.cs

**Comment by lurumad** [comment]
Hi @risogolo 

You can configure it using StoreOptions:

```csharp
.AddEntityFrameworkCoreStore(options =>
                {
                    options.DefaultSchema = "yourschema";
                    options.ConfigureDbContext = (builder) =>
                    {
                        builder.UseSqlServer(Configuration.GetConnectionString("Esquio"));
                    };
                })
```

Regards!

**Comment by risogolo** [comment]
this is when you set which schema to read from, but If I understand this correcly currently the db tables are created only from UI project and there is no option to name the schema for creation.

**Comment by unaizorrilla** [comment]
Yeap, I hope Esquio 3, we are planing to release in May solve this issue and improve the experience with this!

**Comment by unaizorrilla** [comment]
Already pushed on Esquio 3!  Preview version are on NuGet right now!
