### ISSUE TITLE
AddConfigurationStore() is missing when following the "Getting Started" guide

### ISSUE THREAD

**Issue by tiesmaster** [Xabaril/Esquio#90]
I was trying to get started with Esquio, however, when following the [Getting Started guide](https://esquio.readthedocs.io/en/latest/started/aspnetcore.html) for ASP.NET Core, I got compilation errors on the `.AddConfigurationStore()` bit.

Turns out you also need to pull in the `Esquio.Configuration.Store` package, which defines this extension method. Is there a dependency missing on the "meta package", or should the docs be expanded with this detail?

**Comment by lurumad** [comment]
Hi @tiesmaster 

You are right! We need to update the docs.

Regards!

**Comment by tiesmaster** [comment]
That was fast 😅 Very nice :)
